spring.data.mongodb.database=smarttask
spring.data.mongodb.uri=mongoDB_url
spring.mongodb.database=smartassign
server.port=8080
logging.level.org.springframework=INFO
logging.level.com.smartassign=DEBUG

