spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:smarttask}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:smartassign}
server.port=${SERVER_PORT:8080}
logging.level.org.springframework=INFO
logging.level.com.smartassign=DEBUG
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL:gpt-3.5-turbo}

